nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs
npmRegistryServer: https://mirrors.cloud.tencent.com/npm/
npmScopes:
  babel:
    npmRegistryServer: "https://mirrors.huaweicloud.com/repository/npm/"